# Generated by Django 4.2.2 on 2023-08-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_Spendings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spendings', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('peripherals_total_spendings', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=6, null=True)),
                ('spare_parts_total_spendings', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=6, null=True)),
                ('software_total_spendings', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=6, null=True)),
                ('windows_spending', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Total Spendings',
                'verbose_name_plural': 'Total Spendings',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='total_spendings',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.total_spendings'),
        ),
    ]
