# Generated by Django 4.2.2 on 2023-08-20 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_total_spendings_device_total_spendings'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_spendings',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='total_spendings',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
