# Generated by Django 4.2.2 on 2023-08-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_android_name_remove_android_remark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refurbished_Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Refurbished Device',
                'verbose_name_plural': 'Refurbished Devices',
            },
        ),
        migrations.CreateModel(
            name='Scrapped_Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Scrapped Device',
                'verbose_name_plural': 'Scrapped Devices',
            },
        ),
    ]
