# Generated by Django 4.2.2 on 2023-08-20 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_anything_request_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporate_donor',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.corporate_type'),
        ),
        migrations.AlterField(
            model_name='device_refurbishment_request_details',
            name='corporate_donor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.corporate_donor'),
        ),
        migrations.AlterField(
            model_name='windows',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.device'),
        ),
    ]
