# Generated by Django 4.2.2 on 2023-08-20 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_corporate_donor_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='corporate_donor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.corporate_donor'),
        ),
        migrations.AlterField(
            model_name='device',
            name='individual_donor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.individual_donor'),
        ),
        migrations.AlterField(
            model_name='device',
            name='refurbished',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.refurbished_device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='scrapped',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.scrapped_device'),
        ),
    ]
