# Generated by Django 4.2.2 on 2023-08-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_ram_size_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_spendings',
            name='peripherals_total_spendings',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='total_spendings',
            name='software_total_spendings',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='total_spendings',
            name='spare_parts_total_spendings',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='total_spendings',
            name='windows_spending',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
    ]
