# Generated by Django 4.2.2 on 2023-08-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_total_spendings_spare_parts_total_spendings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_spendings',
            name='peripherals_total_spendings',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='total_spendings',
            name='software_total_spendings',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='total_spendings',
            name='spare_parts_total_spendings',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='total_spendings',
            name='total_spendings',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='total_spendings',
            name='windows_spending',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
    ]
