# Generated by Django 4.2.2 on 2023-08-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_total_spendings_peripherals_total_spendings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_spendings',
            name='spare_parts_total_spendings',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
    ]
