from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('home/', views.home, name='home'),
    path('add-device/', views.addDevice, name='add-device'),            # TODO REMOVE
    path('manager/', views.home_manager, name='manager'),
    path('manager/change-prices/', views.manager_change_prices, name='manager-change-prices'),
    path('manager/change-prices/windows/', views.manager_change_windows_price, name='manager-change-windows-price'),
    path('manager/change-prices/peripherals/', views.manager_change_peripherals_prices_list, name="manager-change-peripherals-prices"),
    path('manager/change-prices/peripherals/<int:peripheral_id>/', views.manager_change_price_of_peripheral, name="manager-change-price-of-peripheral"),
    path('manager/change-prices/spare-parts/', views.manager_change_spart_parts_prices_list, name='manager-change-spare-parts-prices-list'),
    path('manager/change-prices/spare-parts/<int:spare_part_id>/', views.manager_change_price_of_spare_part, name='manager-change-price-of-spare-part'),
    path('manager/all-added-devices-list/', views.manager_all_added_devices_list, name="manager-all-added-devices-list"),
    path('manager/general-statistics/', views.manager_general_statistics, name="manager-general-statistics"),
    path('warehouse/', views.warehouse, name='warehouse'),
    path('warehouse/request-device-refurbishment/', views.request_devices_refurbishments, name='request-device-refurbishment'),
    path('warehouse/request-peripheral-inspection/', views.request_peripheral_inspection, name='request-peripheral-inspection'),
    path('warehouse/request-anything/', views.request_anything, name='warehouse-request-anything'),
    path('warehouse/my-requests/', views.warehouse_my_requests_main, name='warehouse-my-requests-main'),
    path('warehouse/my-requests/devices-refurbishments/', views.warehouse_my_requests_device_refurbishment_requests, name='warehouse-device-refurbishment-requests'),
    path('warehouse/my-requests/devices-refurbishments/<int:request_id>/', views.warehouse_device_refurbishment_request_details, name='warehouse-device-refurbishment-request-details'),
    path('warehouse/my-requests/peripherals-inspections/', views.warehouse_peripherals_inspection_requests, name='warehouse-peripheral-inspection-requests'),
    path('warehouse/my-requests/peripherals-inspections/<int:request_id>/', views.warehouse_peripherals_inspection_request_details, name='warehouse-peripheral-inspection-request-details'),
    path('warehouse/my-requests/anything/', views.warehouse_anything_requests_list, name='warehouse-anything-requests'),
    path('warehouse/my-requests/anything/<int:request_id>/', views.warehouse_anything_request_details, name='warehouse-anything-request-details'),
    path('operation-lab/', views.operation_lab, name='operation-lab'),
    path('operation-lab/add-device/', views.operation_lab_add_device, name='operation-lab-add-device'),
    path('operation-lab/request-spare-parts-peripherals-devices/', views.operation_lab_request_spare_part_peripheral_device, name='request-spare-parts-peripherals-devices'),
    path('operation-lab/request-anything/', views.request_anything, name='operation-lab-request-anything'),
    path('operation-lab/my-requests/', views.operation_lab_my_requests_main, name='operation-lab-my-requests-main'),
    path('operation-lab/my-requests/spare-parts-peripherals-devices/', views.operation_lab_my_requets_spare_parts_peripherals_devices_request, name='operation-lab-my-requests-spare-parts-peripherals-devices-request'),
    path('operation-lab/my-requests/spare-parts-peripherals-devices/<int:request_id>/', views.operation_lab_sp_p_d_request_details, name='operation-lab-sp-p-d-request-details'),
    path('operation-lab/my-requests/anything/', views.operation_lab_anything_requests, name="operation-lab-anything-requests-list"),
    path('operation-lab/my-requests/anything/<int:request_id>/', views.operation_lab_anything_requests_details, name='opeation-lab-anything-request-details'),
    path('operation-lab/devices-added-by-me/', views.operation_lab_devices_added_by_user_list, name='devices-added-by-user-list'),
    path('operation-lab/devices-added-by-me/id-<int:device_id>', views.operation_lab_device_added_by_user_details, name='devices-added-by-user-details'),
    path('manager/charts/chart-2/', views.manager_chart_2, name='manager-chart-2'),
]